#
# Tomcat-Slf4j-Logback (https://github.com/tomcat-slf4j-logback/tomcat7-slf4j-logback/)
#
# Copyright (c) 2010-2020 Tomcat-Slf4j-Logback.
#
# All rights reserved. This program and the accompanying materials are made available under the
# terms of the Eclipse Public License v1.0 which accompanies this distribution, and is available
# at https://www.eclipse.org/legal/epl-v10.html.
#
# Contributors: Tomcat-Slf4j-Logback Team.
#

version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.apache.tomcat:tomcat-juli
    versions:
    - "> 7.1.0"
